version: '3.8'
services:
  backend:
    build: ../backend
    ports:
      - '4000:4000'
    volumes:
      - ../backend:/app

  frontend:
    image: nginx:stable-alpine
    ports:
      - '3000:80'
    volumes:
      - ../frontend/public:/usr/share/nginx/html:ro
